spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${nft.turbo.nacos.server.url} #首次启动前务必修改成你自己的
      config:
        server-addr: ${nft.turbo.nacos.server.url} #首次启动前务必修改成你自己的
        file-extension: properties
        name: ${spring.application.name}