spring:
  application:
    name: @application.name@
  config:
    import: classpath:base.yml,classpath:datasource.yml,classpath:cache.yml,classpath:bot.yml

server:
  port: 8085

dubbo:
  application:
    qos-port: 33334